inherits = "my_solarized_light"

[pallette]
base03 = "#002d38"
base02 = "#093946"
base01 = "#5b7279"
base00 = "#657377"
base0 = "#98a8a8"
base1 = "#8faaab"
base2 = "#f1e9d2"
base3 = "#fbf7ef"
yellow = "#ac8300"
orange = "#d56500"
red = "#f23749"
magenta = "#dd459d"
violet = "#7d80d1"
blue = "#2b90d8"
cyan = "#259d94"
green = "#819500"
