# Syntax Highlighting
"attribute" = {}

"type.builtin" = {}
"type.parameter" = {}
"type.enum" = {}
"type.enum.variant" = {}

"constructor" = {}

"constant" = {}
"constant.builtin" = {}
"constant.builtin.boolean" = {}
"constant.character" = {}
"constant.character.escape" = {}
"constant.numeric" = {}
"constant.numeric.integer" = {}
"constant.numeric.float" = {}

"string" = {}
"string.regexp" = {}
"string.special" = {}
"string.special.path" = {}
"string.special.url" = {}
"string.special.symbol" = {}

"comment" = {}
"comment.line" = {}
"comment.block" = {}
"comment.block.documentation" = {}

"variable" = {}
"variable.builtin" = {}
"variable.parameter" = {}
"variable.other" = {}
"variable.other.member" = {}

"label" = {}

"punctuation" = {}
"punctuation.delimiter" = {}
"punctuation.bracket" = {}
"punctuation.special" = {}

"keyword" = {}
"keyword.control" = {}
"keyword.control.conditional" = {}
"keyword.control.repeat" = {}
"keyword.control.import" = {}
"keyword.control.return" = {}
"keyword.control.exception" = {}
"keyword.operator" = {}
"keyword.directive" = {}
"keyword.function" = {}
"keyword.storage" = {}
"keyword.storage.type" = {}
"keyword.storage.modifier" = {}

"operator" = {}

"function" = {}
"function.builtin" = {}
"function.method" = {}
"function.macro" = {}
"function.special" = {}

"tag" = {}
"tag.builtin" = {}

"namespace" = {}

"special" = {}

"markup" = {}
"markup.heading" = {}
"markup.heading.marker" = {}
"markup.heading.1" = {}
"markup.heading.2" = {}
"markup.heading.3" = {}
"markup.heading.4" = {}
"markup.heading.5" = {}
"markup.heading.6" = {}
"markup.list" = {}
"markup.list.unnumbered" = {}
"markup.list.numbered" = {}
"markup.list.checked" = {}
"markup.list.unchecked" = {}
"markup.bold" = {}
"markup.italic" = {}
"markup.strikethrough" = {}
"markup.link" = {}
"markup.link.url" = {}
"markup.link.label" = {}
"markup.link.text" = {}
"markup.quote" = {}
"markup.raw" = {}
"markup.raw.inline" = {}
"markup.raw.block" = {}

"diff" = {}
"diff.plus" = {}
"diff.plus.gutter" = {}
"diff.minus" = {}
"diff.minus.gutter" = {}
"diff.delta" = {}
"diff.delta.moved" = {}
"diff.delta.gutter" = {}

# Interface
"markup.normal" = {}
"markup.normal.completion" = {}
"markup.normal.hover" = {}
"markup.heading.completion" = {}
"markup.heading.hover" = {}
"markup.raw.completion" = {}
"markup.raw.hover" = {}

# UI
"ui.background" = {}
"ui.background.separator" = {}
"ui.cursor" = {}
"ui.cursor.normal" = {}
"ui.cursor.insert" = {}
"ui.cursor.select" = {}
"ui.cursor.match" = {}
"ui.cursor.primary" = {}
"ui.cursor.primary.normal" = {}
"ui.cursor.primary.insert" = {}
"ui.cursor.primary.select" = {}
"ui.debug.breakpoint" = {}
"ui.debug.active" = {}
"ui.gutter" = {}
"ui.gutter.selected" = {}
"ui.highlight.frameline" = {}
"ui.linenr" = {}
"ui.linenr.selected" = {}
"ui.statusline" = {}
"ui.statusline.inactive" = {}
"ui.statusline.normal" = {}
"ui.statusline.insert" = {}
"ui.statusline.select" = {}
"ui.statusline.separator" = {}
"ui.bufferline" = {}
"ui.bufferline.active" = {}
"ui.bufferline.background" = {}
"ui.popup" = {}
"ui.popup.info" = {}
"ui.window" = {}
"ui.help" = {}
"ui.text" = {}
"ui.text.focus" = {}
"ui.text.inactive" = {}
"ui.text.info" = {}
"ui.virtual.ruler" = {}
"ui.virtual.whitespace" = {}
"ui.virtual.indent-guide" = {}
"ui.virtual.inlay-hint" = {}
"ui.virtual.inlay-hint.parameter" = {}
"ui.virtual.inlay-hint.type" = {}
"ui.virtual.wrap" = {}
"ui.menu" = {}
"ui.menu.selected" = {}
"ui.menu.scroll" = {}
"ui.selection" = {}
"ui.selection.primary" = {}
"ui.highlight" = {}
"ui.cursorline.primary" = {}
"ui.cursorline.secondary" = {}
"ui.cursorcolumn.secondary" = {}

"warning" = {}
"error" = {}
"info" = {}
"hint" = {}
"diagnostic" = {}
"diagnostic.hint" = {}
"diagnostic.info" = {}
"diagnostic.warning" = {}
"diagnostic.error" = {}
