[colors]
ansi = [
    "#7970A9",
    "#FF9580",
    "#8AFF80",
    "#FFFF80",
    "#9580FF",
    "#FF80BF",
    "#80FFEA",
    "#F8F8F2",
]
background = '#22221C'
brights = [

    "#7970A9",
    "#FFAA99",
    "#A2FF99",
    "#FFFF99",
    "#AA99FF",
    "#FF99CC",
    "#99FFEE",
    "#FFFFFF",
]
compose_cursor = '#ffb86c'
cursor_bg = '#f8f8f2'
cursor_border = '#f8f8f2'
cursor_fg = '#282a36'
foreground = '#f8f8f2'
scrollbar_thumb = '#44475a'
selection_bg = '#454158'
selection_fg = 'rgba(0% 0% 0% 0%)'
split = '#6272a4'

[colors.indexed]

[colors.tab_bar]
background = '#282a36'

[colors.tab_bar.active_tab]
bg_color = '#bd93f9'
fg_color = '#282a36'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#282a36'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#6272a4'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#282a36'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ff79c6'
fg_color = '#f8f8f2'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'timescam'
name = 'Nosferatu'
origin_url = 'https://github.com/dracula/wezterm'
